theme = "lynx"
title = "CV"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Chris Van Dusen"
  headline = "My Name Is Chris"
  image = "author.jpg"
  links = [
    { email = "mailto:chris@cvandusen.com"},
    #{ link = { href = "https://d3nbhefp0ez0gn.cloudfront.net/protected/hvZEjdlEUlzAKE/contact_1697210719923.vcard", text = "Contact Info", icon = "github" } },
    #{ link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { linkedin = "https://www.linkedin.com/in/cvanduse/"},
    { twitter = "https://twitter.com/fwd2cv" },
    { instagram = "https://instagram.com/fwd2cv" },
    #{ font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
{ spotify-player = { href = "https://open.spotify.com/user/316uxgvzpdayob4lt57ph4dpzby4", text = "Spotify" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
